server:
  port: 9999
  servlet:
    context-path: /tyh

mybatis:
  #注册映射文件
  mapper-locations: classpath:com/abc/dao/*.xml
  #注册实体类别名
  type-aliases-package: com.abc.bean

spring:
  #注册数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456

  #  连接单机Redis
  redis:
    host: localhost
    port: 16379

  cache:
    #    指定当前应用所使用的缓存类型
    type: redis
    #    指定当前应用所使用的缓存区域名称
    cache-names: realTimeCache

  application:
    # 相当于<dubbo:application/>标签
    name: t12-dubbo-provider

  dubbo:
    # 注册zk注册中心
    registry: zookeeper://localhost:2181
    # registry: zookeeper://zkOS1:2181?backup=zkOS2:2181,zkOS3:2181