server:
  port: 8888
  servlet:
    context-path: /tyh

spring:
  application:
    name: t12-dubbo-consumer

  dubbo:
    # 注册zk注册中心
    registry: zookeeper://localhost:2181
    # registry: zookeeper://zkOS1:2181?backup=zkOS2:2181,zkOS3:2181
  mvc:
    view:
      prefix: /
      suffix: .jsp